development:
  adapter: postgresql
  encoding: unicode
  database: insta
  pool: 5
  host: localhost
  port: 5432
  username: oleg
  password: qwerty123


test:
  adapter: postgresql
  encoding: unicode
  database: insta
  pool: 5
  host: localhost
  port: 5432
  username: oleg
  password: qwerty123